CREATE TABLE IF NOT EXISTS 
PurchaseOrder(
	POID TEXT PRIMARY KEY,   
	SupplierID TEXT, 
	PODate DATE, 
	Approval TEXT,
	Done BOOLEAN,
	FOREIGN KEY(SupplierID) REFERENCES Supplier(SupplierID)
	);

CREATE TABLE IF NOT EXISTS
SKU(
	SKUID TEXT PRIMARY KEY,
	SKUName TEXT,
	OpeningStock FLOAT,
	CurrentStockLvl FLOAT
	);

CREATE TABLE IF NOT EXISTS
Supplier(
	SupplierID TEXT PRIMARY KEY,
	SupplierName TEXT
	);

CREATE TABLE IF NOT EXISTS
SalesOrder(
	SOID TEXT PRIMARY KEY,
	SODate DATE
	);

CREATE TABLE IF NOT EXISTS
Staff(
	StaffID TEXT PRIMARY KEY,
	StaffFirstName TEXT,
	StaffLastName TEXT,
	Position TEXT,
	AccessLvl TEXT,
	Username TEXT,
	Pw TEXT,
	Email TEXT,
	Lock BOOLEAN
	);

CREATE TABLE IF NOT EXISTS
POSKU(
	POSKUID INTEGER PRIMARY KEY NOT NULL,
	POID TEXT,
	SKUID TEXT,
	Qty INT, 
	TtlPurchasePrice REAL, 
	ExpArrDate DATE,
	ArrStatus TEXT,
	FOREIGN KEY(POID) REFERENCES PurchaseOrder(POID),
	FOREIGN KEY(SKUID) REFERENCES SKU(SKUID)
);

CREATE TABLE IF NOT EXISTS
SOSKU(
	SOSKUID INTEGER PRIMARY KEY NOT NULL,
	SOID TEXT,
	SKUID TEXT,
	Qty REAL,
	TtlSellingPrice REAL,
	DeliveryDate DATE,
	DeliveryStatus TEXT,
	FOREIGN KEY(SOID) REFERENCES SalesOrder(SOID),
	FOREIGN KEY(SKUID) REFERENCES SKU(SKUID)
);

CREATE TABLE IF NOT EXISTS
GRN(
	GRNNo TEXT NOT NULL PRIMARY KEY,
	POSKUID INTEGER NOT NULL,
	ActArrDate DATE,
	CONSTRAINT POSKUID FOREIGN KEY (POSKUID) REFERENCES POSKU(POSKUID),
	CONSTRAINT UniqFK UNIQUE (POSKUID)
);

CREATE TABLE IF NOT EXISTS
SPECIAL(
	SpecialDate DATE NOT NULL PRIMARY KEY,
	VIP INTEGER,
	SD1 INTEGER,
	SD2 INTEGER
);